# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: MSCRMToolInstaller@12
  inputs:
    nugetFeed: 'official'
    psFeed: 'official'
- task: MSCRMExportSolution@12
  inputs:
    crmConnectionString: 'AuthType=OAuth;Username=testraj@rajtextop.onmicrosoft.com; Password=Driku@2019;Url=https://org7ff909af.crm8.dynamics.com'
    solutionName: 'Dynamic365Sol'
    exportManaged: false
    exportUnmanaged: true
    outputPath: '$(build.binariesdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'